### ISSUE TITLE
Todo list for SetTheory/Game

### ISSUE THREAD

**Issue by timotree3** [leanprover-community/mathlib4#10611]
I want to use this issue to summarize the discussion in [the Zulip thread for `SetTheory/Game`](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames). (Individual Zulip links are to specific messages)

Extensional equivalence of `PGame`s:
- [x] Introduce `Identical : PGame -> PGame -> Prop` for extensional equivalence of `PGames` (identifying games with equivalent sets of left and right moves). This corresponds to "identical" games as referred to by Conway. #5901 
  - [ ] Remove `Relabelling` which is a weaker of extensional equivalence and has no equivalent in set theoretic foundations. [Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames/near/290532313)
- [ ] Redefine `Short` as games with finite birthday. The current definition does not respect extensional equivalence of `PGame`s and therefore has no correspondence to the literature. [Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames/near/290536792) - #7162 
- [ ] Introduce `IGame` as the quotient of `PGame` by `Identical` #14760

Since `PGame` is really just an implemention detail due to our type-theoretic foundations, it would be nice if we could quickly define `IGame` in terms of it and build up the API around `IGame` without continuing to refer to the underlying definition. To achieve this, the following refactor would be possible:
- [ ] Introduce a type of "small sets" or "indexed sets" - sets of `α : Type u` (where `u` is a big universe) which have small enough cardinality to have models in a smaller universe. [Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames/near/285623567) - #10609
- [ ] Refactor `IGame` to have its foundational API in terms of `SmallSet`:
  - Just after defining `IGame` prove `IGame.{u} ≃ SmallSet.{u} IGame × SmallSet.{u} IGame` (with the two sets represent the left and right moves)
  - Prove that the "subsequent" relation on `IGame`s is well-founded and use that for any recursive definitions thereafter

Streamlining lemmas about the order of `PGame`/`IGame`:
- [ ] Define `cmp : IGame -> IGame -> CmpResult` where `CmpResult` is either less-than, equivalent, greater-than, or fuzzy. Use this definition to simplify casework in later proofs. [Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames/near/287466439)

Generalizing definitions on `PGame`/`IGame` to any `Preorder`:
- [ ] Generalize `cmp` (once defined) to any `Preorder`. [Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames/near/287516895)
- [ ] Replace `PGame.Equiv` with `AntisymmRel (· ≤ ·)` and redefine `Game` as `Antisymmetrization PGame` 
- [ ] Generalize `LF` (less-than or fuzzy) to be defined for any `Preorder`?
  - Maybe not. The name "fuzzy" doesn't mean much outside of the context of games. [Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Well-founded.20recursion.20for.20pgames/near/287516734)
  - Also define the notation `(· ⧏ ·)` for any `Preorder`? (Maybe scoped?)

cc @alreadydone @FR-vdash-bot @YaelDillies @vihdzp - Let me know if you agree with these TODOs

**Comment by YaelDillies** [comment]
Note that `PGame.Equiv` is already generalised to any preorder, see `AntisymmRel`. You should replace that TODO by
* Redefine `Game` as `Antisymmetrization PGame`

**Comment by vihdzp** [comment]
This list is definitely a bit outdated. Still, here's my opinions:
- It seems that `SmallSet` was not meant to be. We definitely still want `IGame`, though.
- I don't think an lt/equiv/gt/fuzzy operator would be very useful. We can get the same functionality by just asking whether `a < b` and `b < a`, each of the four possible answers gives us one of the four relations.
- I'm working on redefining `Game` as the antisymmetrization of `PGame`. #19571 ports all of the `PGame.equiv` API to `AntisymmRel`, after which point this should be a relatively straightforward task.
- `a ⧏ b` is just syntax "sugar" for `¬ b < a`, so it really doesn't need to be generalized. Likewise, we should get rid of `PGame.LF` and `Game.LF`, even though we can keep the notation if we really want to.

**Comment by vihdzp** [comment]
Closing this issue, since development of CGT will provisionally continue over at a new repo. 
Feel free to update this list and open and issue there!

https://github.com/vihdzp/combinatorial-games
