### ISSUE TITLE
Porting library notes - tracking issue

### ISSUE THREAD

**Issue by timotree3** [leanprover-community/mathlib4#10968]
The following library notes were present in mathlib3 but missing in mathlib4, despite being referred to with `See note [...]`:
- [ ] [function coercion](https://leanprover-community.github.io/mathlib_docs/notes.html#function%20coercion)
- [ ] [implicit instance arguments](https://leanprover-community.github.io/mathlib_docs/notes.html#implicit%20instance%20arguments)
- [ ] [lower instance priority](https://leanprover-community.github.io/mathlib_docs/notes.html#lower%20instance%20priority)
- [ ] [nolint_ge](https://leanprover-community.github.io/mathlib_docs/notes.html#nolint_ge)
- [ ] [partially-applied ext lemmas](https://leanprover-community.github.io/mathlib_docs/notes.html#partially-applied%20ext%20lemmas)
- [ ] [simp-normal form](https://leanprover-community.github.io/mathlib_docs/notes.html#simp-normal%20form)
- [ ] [use has_coe_t](https://leanprover-community.github.io/mathlib_docs/notes.html#use%20has_coe_t)

The following were present in mathlib3 and are missing in mathlib4, but are also not referred to anywhere in mathlib4:
- [likely generated binder names](https://leanprover-community.github.io/mathlib_docs/notes.html#likely%20generated%20binder%20names)
- [open expressions](https://leanprover-community.github.io/mathlib_docs/notes.html#open%20expressions)
- [user attribute parameters](https://leanprover-community.github.io/mathlib_docs/notes.html#user%20attribute%20parameters)
