### ISSUE TITLE
"basic" extensions for `positivity` tactic

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover-community/mathlib4#1101]
Some extensions for the `positivity` tactic deal with more advanced mathematics, and are implemented in-place in the library as the concepts are defined.  Others deal with basic mathematics and in mathlib3 were implemented in the file `tactic/positivity`.

In mathlib4, the corresponding file is `Tactic/Positivity/Basic`.  However, not all the "basic" positivity extensions are implemented there yet.  The missing ones are
- [x] min
- [x] max
- [x] div and int-div
- [x] inv
- [x] zpow (we do have nat powers)
- [x] abs
- [x] nat_abs
- [x] coercions from nats, ints, rationals (this might behave differently in Lean 4). (done in #2402, #8042)
- [x] nat.succ
- [x] factorial and asc_factorial
- [ ] instances of `OrderAddMonoidHomClass`

I think that all of these now have the underlying theory ported that they would need, ~~with the exception of `div` (probably blocked by #1065), `zpow` (a couple of files down the chain from that), and casts of rationals (a couple of files down the chain from #998).~~

**Comment by dwrensha** [comment]
`abs` and `inv` are in #1190.

**Comment by dwrensha** [comment]
div and int-div are in #1391.

**Comment by dwrensha** [comment]
`min` is in #1401.

**Comment by hrmacbeth** [comment]
#3907 has `NonnegHomClass` (this includes `AbsoluteValue` and `Seminorm`), norm, the `NNReal`-to-`Real` coercion, square roots, distance (in a metric space), and diameter.
