### ISSUE TITLE
Tracking issue: Ordinal refactors

### ISSUE THREAD

**Issue by vihdzp** [leanprover-community/mathlib4#17033]
This issue keeps track of various miscellaneous planned refactors to the `Ordinal` part of the library, mostly cleaning up definitions that should be replaced with more general concepts.
- [x] Deprecate `Ordinal.sup`: #15820
- [ ] Deprecate `Ordinal.bsup`
- [ ] Deprecate `Ordinal.lsub` and `Ordinal.blsub`
- [ ] Deprecate `Ordinal.mex` and `Ordinal.bmex`: #16989
- [ ] Deprecate the `BFamily` API
- [ ] Change `Set.Unbounded (· < ·)` to `¬ BddAbove`: #16962
- [ ] Replace `Ordinal.IsLimit` by `Order.IsSuccLimit`
- [ ] Replace `Order.succ x` by `x + 1`

Some bonus stuff which probably needs to be discussed beforehand.
- [ ] Replace `Ordinal.nfp` by `OmegaCompletePartialOrder.fixedPoints.iterateChain`
- [ ] Redefine `Cardinal.univ` in terms of `#Cardinal`
- [ ] Generalize `Ordinal.pred` to preorders
