### ISSUE TITLE
Tracking Issue: Combinatorial Game Theory

### ISSUE THREAD

**Issue by tristan-f-r** [leanprover-community/mathlib4#18161]
This keeps track of some missing concepts in combinatorial game theory, including mentions in `PGame`'s [future work](https://github.com/leanprover-community/mathlib4/blob/f375907aff43996d648bf90dc95bc2c89e50626e/Mathlib/SetTheory/Game/PGame.lean#L84) section

- [ ] The theory of dominated, reversible positions, and unique normal form for short games.
- [ ] Analysis of basic domineering positions
- [ ] Board-splitting utilities (for Chomp, Domineering, Nim, Sprouts)
- [ ] Temperature
- [ ] Loopy games
  - [ ] Stopper games
- [ ] Impartialness via the equivalence of L/R moves
- [ ] Strategy Stealing Argument (Chomp/Hex as examples)
- [ ] Pairing Strategy for State games (unsure what the typical example is here for normal-play games, but perhaps Tic-Tac-Toe for a positional game?)
- [ ] Non-normal-play short games
- [ ] Game Stops
- [ ] Tiny & Miny games
- [ ] Lawnmower theorem

Game archive:

- [ ] (discuss) Move domineering to the Archive?
- [ ] Proof of Sim's inability to tie via Ramsey Theory
  - [ ] Proof of Sim winning by the 2nd player? (This seems to be done by computer search only)
- [ ] Sprouts
  - [ ] Proof of winning state for Brussel Sprouts despite suboptimal play

**Comment by vihdzp** [comment]
Just seeing this now!

Combinatorial game theory is full of a lot of quirky games, but I think most of these aren't really useful for anything else. Perhaps we can create a game folder in the archive to house these sorts of results?

Chomp (or really, its generalization of the poset game) seems by far like the easiest one to formalize. By doing this, we even get all-green Hackenbush for free. The only thing I'm unsure of is: what are the conditions required for the game to terminate? A finite poset is sufficient but not necessary, as e.g. you can play Chomp on any n-dimensional "cuboid" with ordinal dimensions. Is the required condition that the poset be well-founded?

We already have Nim and Domineering in Mathlib. What sort of "board-splitting" utilities do you want on them? Do you just want some sort of result that expresses a position as the sum of other positions?

I'm not very familiar with all of the other described concepts. Feel free to discuss on Zulip if you have any plans for them!

**Comment by LeoDog896** [comment]
Sure! I'll open a zulip thread sometime soon for this discussion, but for the other questions you just asked:

> Combinatorial game theory is full of a lot of quirky games, but I think most of these aren't really useful for anything else. Perhaps we can create a game folder in the archive to house these sorts of results?

Absolutely!

> Chomp (or really, its generalization of the poset game) seems by far like the easiest one to formalize. By doing this, we even get all-green Hackenbush for free. The only thing I'm unsure of is: what are the conditions required for the game to terminate? A finite poset is sufficient but not necessary, as e.g. you can play Chomp on any n-dimensional "cuboid" with ordinal dimensions. Is the required condition that the poset be well-founded?

The poset games (Chomp) was the first game I wanted to formalize!

> We already have Nim and Domineering in Mathlib. What sort of "board-splitting" utilities do you want on them? Do you just want some sort of result that expresses a position as the sum of other positions?

I believe I said that bulleted point wrong; I'll remove it, but I meant it as certain games (i.e. Nim, Domineering, Cram, Sprouts) to have theorems that show that some games are equal to sums of its own instance.

> I'm not very familiar with all of the other described concepts. Feel free to discuss on Zulip if you have any plans for them!

Sure! One of the other parts I was interested in formalizing was the loopy games, though that requires a multigraph with labelled edges which I'm unsure if lean4 has.

**Comment by vihdzp** [comment]
Do you think you could re-write this list as an issue on our new CGT repo?
