### ISSUE TITLE
Define actions of `DomMulAct` on bundled homs

### ISSUE THREAD

**Issue by urkud** [leanprover-community/mathlib4#5379]
This issue keeps track of missing instances for actions of `Mᵈᵐᵃ` on
function spaces.

- [ ] action on `α → β`, see #5368;
- [ ] a `MulDistribMulAction` generates an action on `A →* B`, see #5368;
- [ ] a `DistribMulAction` generates an action on `A →+ B`, see #5368;
- [ ] an action on `α` that commutes with action of some other monoid `N` generates an action on
	`α →[N] β`, see #5378;
- [ ] a `DistribMulAction` on an `R`-module that commutes with scalar multiplications by `c : R`
  generates an action on `R`-linear maps from this module;
- [ ] a continuous action on `X` generates an action on `C(X, Y)`;
- [ ] a measurable action on `X` generates an action on `{ f : X → Y // Measurable f }`;
- [ ] a quasi measure preserving action on `X` generates an action on `X →ₘ[μ] Y`;
- [ ] a measure preserving action generates an isometric action on `MeasureTheory.Lp _ _ _`.

**Comment by EzequielS2** [comment]
I'll work on this.
