### ISSUE TITLE
Autogenerate lemmas about `OfNat.ofNat`

### ISSUE THREAD

**Issue by urkud** [leanprover-community/mathlib4#8135]
Add a command or an attribute that generates lemmas about `OfNat.ofNat` from lemmas about `Nat.cast`.

The initial version should work if the original lemma has exactly one argument `n` of type `Nat`.
It should:

- [ ] add `[n.AtLeastTwo]` assumption;
- [ ] replace all occurrences of `Nat.cast n` with `OfNat.ofNat n`;
- [ ] drop the following assumptions proving them using `[n.AtLeastTwo]`:
  - [ ] `n ≠ 0`
  - [ ] `0 < n`
  - [ ] `n ≠ 1`
  - [ ] `1 < n`
  - [ ] `2 ≤ n`
- [ ] prove the resulting lemma by defeq to the old lemma;
- [ ] in case of a `simp` lemma, add `no_index` as needed;
- [ ] find one of `nat_cast` or `coe_nat` or `nat_coe` or `nat` in the name and replace it with `ofNat`.

Optional features:

- [ ] deal with two natural numbers (should we replace both with `ofNat` or generate 3 versions?)
- [ ] allow some customization (not sure what will be needed in real life).

**Comment by timotree3** [comment]
Eventually it might be nice if this generated lemmas for `0` and `1` as well as numbers at least two. This is complicated by a few factors

- `0`/`1` is not always defeq to `Nat.cast 0`/`Nat.cast 1`. (e.g. `(1 : Ordinal)` is not defeq to `((1 : Nat) : Ordinal)`)
- Sometimes a lemma for `0` or `1` already exists because it was used to prove the general lemma for `n`
- Sometimes a lemma for `0` or `1` is unneeded because it's implied by more general lemmas (e.g. because the lemma is about `f n` where `f : AddMonoidHom`, so the zero case is implied by `map_zero`)
